image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - eval $(ssh-agent -s)
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
  - hugo
  - scp public/* beeblebrox-web@beeblebrox.ch:/volume2/web/beeblebrox/
  artifacts:
    paths:
    - public
  only:
  - master