dist: xenial

addons:
  snaps:
  - hugo

env:
  matrix:
    secure: "mxANGWtSI05kLhg7UAZP5Cu3n2hRbJ4nHIVPdorDzuf+bYDFzVyp9oGFQCwErAZHWOalgQF2cybnJyqVjbpqU+Z0T9fHJdJxKgA8xwRxPbQZqumv+OfKaLInlQr0nUvWvxTJFjZcoaRX1MbK83Big41Swg/HR5GPDC9uSjKXl08mTRIKHyOkZoSMmDoe16+wC6Bmi5NqgZzTbo5h1K83nWqD9TowhYFJ9YcrH/9Jbrbf1tKMRLndDAz2OPwd1tKP0dLyCKmRRznZsrV8SX/GloVsSxa4bOUPm+toM8a4KpXxdi/+W1td6RuRI5RUOyQkcRW93vdtVqsY5wNO40d9svjhTEt99hw3c8lMzpYmdyCGdo+vdnTleK5gD1Vmk8eglcbt3Qnv37cIxmICm7+ecQWMIqKljb65FfOGbfBFz/4+7AgdTwRoFdfzMXXNSTHMH+vlTQaYxLO447YSXl/l7wJKJmlMfjZFODd1d/1u0tYUOjvn/BFJx54wn9iELqnvC15aCUAhK2JQTELpqw06a2kXITz9sOystiCl+07cRbg7NY/ZZqtAkv/3CNtgqXOgFPHfSdhJ0EmK0kWwQxIPFYKgWNtvcsdbjgoUN9FejGVuEhxhCkGz2F15f54CiNTFYaS4vfpovmFA2ycyH8QqWu5CK53krj5AJ/0/GtFWg8o="

script:
  - hugo

deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  verbose: true
  local-dir: public
  fqdn: xn--htter-kva.ch
  on:
    branch: production
