baseURL = "/"
languageCode = "en-us"
title = "Noah Hütter Portfolio"
theme ="exlodi"
pygmentsCodeFences=true
googleAnalytics = "UA-40883435-8"

paginate = 2

[params]
    # head theme color
    theme_color = "#00ff00"

    # head description
    # This is what appears on the preview when posting this site on Facebook for example
    description = "My Portfolio"

    # head photo
    # This is what appears on the preview when posting this site on Facebook for example
    description_photo = "portrait_800.png"

    # favicon image (512x512px), place this in the static/img folder
    favicon = "tux_pitaya_round-min.png"

    # logo image (204x204px), place this in the static/img folder
    # this appears on the top left of the navigation
    logo = "portrait_800.png"

[params.nav]
 	logoenable = false
    enable = true
    hometext = "hütter.ch"

[params.hero]
    enable = true
    
    # Place this image in the static/img folder
    background = "bgnd2.png"
    avatar = "portrait.png"
    subtitle = "Hi! I'm Noah, an electrical engineer from Zurich, Switzerland."

    # Each element in this array makes a new <p> tag
    # You can write this text in markdown
    hero_right = ["Highly motivated and hardworking **Electrical Engineering** student with excellent grades in both key modules and maths seeking for a career in research and development with demanding challenges.",
    "I currently **study** Electrical Engineering and Information Technology in the Master's degree programme at ETH Zurich.",
    "In my **free time** the fascination of Electronics motivates me to pursue private projects and finance my coffee consumption on freelance colaborations.",
    "Please enjoy the rest of my website."]

    # Link to your resume, place your PDF in the /static folder
    # resume = "resume.pdf"

    # Email
    email = "noah@beeblebrox.ch"

    # Facebook username
    facebook = "https://www.facebook.com/profile.php?id=100012645461001"

    # Twitter username
    twitter = "https://twitter.com/Klavierler"

    # LinkedIn URL
    linkedin = "https://www.linkedin.com/in/noah-h%C3%BCtter-4a8852150/"
    
    # Medium username
    github = "https://github.com/noah95"

    # Buttons
    button1text = "Visit Blog posts"
    button1url = "/posts"

[params.resume]
    enable = true
    title = "Skills"
    subtitle1 = "From professional..."
    subtitle2 = "...to social"

[params.experience]
    enable = true
    title = "Experience"
    subtitle = "Timeline of my Experience"

[params.case_studies]
    enable = true
    title = "Projects"
    subtitle = "Selected projects"

[params.recent_posts]
    enable = true
    title = "Recent posts"
    subtitle = "Subtitle comes here"
    nposts = 4

[params.footer]
    enable = true
