name = "exHugo Lodi Theme"
license = "MIT"
description = "exHugo Lodi Theme extended by Noah Huetter"
tags = ["lodi", "responsive", "hero", "personal", "portfolio", "ux"]
features = ["homepage", "case studies", "process"]
min_version = "0.29"

[author]
  name = "Noah Huetter"
  homepage = "https://beeblebrox.ch"

# If porting an existing theme
[original]
  author = "Alexis Collado"
  name = "Portfolio"
  homepage = "http://www.alexiscollado.com"
